version: '3.8'

services:
    server:
        build: ./
        ports:
            - 80:3000
        depends_on:
            - db
    db: 
        container_name: postgres
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        volumes:
            - './reviews-deployed/:/var/lib/postgresql/data'
        environment:
            POSTGRES_PASSWORD: pawscat
            POSTGRES_USER: postgres
            POSTGRES_DB: greenfield_reviews
    