version: '3.8'

services:
    server:
        container_name: server
        build: .
        ports:
            - 3000:3000
        depends_on:
            - postgres
    postgres: 
        container_name: postgres
        image: postgres:12
        restart: always
        ports:
            - 5432:5432
        volumes:
            - './reviews-deployed/:/var/lib/postgresql/data'
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        