version: '3.8'

services:
    nodejs:
        container_name: nodejs
        image: nodejs:latest
        build:
            context: .
            dockerfile: dockerfile
        restart: always
        env_file: .env
    db: 
        container_name: postgres
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${PGPASSWORD},
            POSTGRES_USER: ${PGUSER}
            POSTGRES_DB: ${PGDATABASE}
        env_file: .env
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    